baseURL = "https://J0SE-ESC0BAR.github.io/"
languageCode = 'es'
title = "JAEM"
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true


# Donde se guardara el contenido generado por Hugo
publishDir = "docs"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 1

[Author]
  name= "José Escobar"

[params]
google_analytics_id = ""
# Hey aquí pon tu twitter 👇
twitter_handle = "@JAEM_Developer"
 showAuthorOnHomepage = true
 showAuthorOnPosts = false
 showPostsOnHomepage = true
 addFrame = true
 addDot = true
 showFooterOnHomepage = true
# agregar hojas de estilo css (array de hojas de estilo)
CSS=["css/estilos.css"]

# agregar mas entradas a la cabezera
#[menu]
#  [[menu.main]]
#    identifier = "contacto1"
#    name = "Contacto1"
#    title = "contacto1"
#    url = "/contacto1/"
#    weight = 0
#  [[menu.main]]
#    identifier = "contacto2"
#    name = "Contacto2"
#    title = "contacto2"
#    url = "/contacto2/"
#    weight = 0