baseURL = "https://j0se-esc0bar.github.io/"
languageCode = 'es'
title = "JAEM"
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true


# Donde se guardara el contenido generado por Hugo
publishDir = "docs"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 6

[Author]
  name= "José Escobar"

[params]
google_analytics_id = ""
# Hey aquí pon tu twitter 👇
twitter_handle = "@JAEM_Developer"
#Ver autor en pagina inicial
showAuthorOnHomepage = true
enableRobotsTXT = true
#Ver autor en posts
showAuthorOnPosts = false

#ver publicaciones en pagina de inicio
showPostsOnHomepage = true

# agregar hojas de estilo css (array de hojas de estilo)
#Contiene bootstrap
css = ["/css/bootstrap.min.css", "/css/styles_manual.css"]
